Restructure README
d3/d3-force pull request #221
Opened 2023-08-08 15:43 UTC by Fil

This proposal:

- Uses h2 and an icon everywhere, for a nice (automated) TOC on GitHub
- Duplicates the 1-line description at the top
- Defers to d3js.org for the API reference (now called Documentation)
- Adds Documentation and Examples links
- Moves Observable to the top of the Installing section

For this particular module, the reference to beeswarm is obsolete. (Though I still like the old beeswarm, and am tempted to make a notebook for it 🤓).

Once we settle on a template, this will have to be replicated to all the modules covered by d3js.org

2023-10-05 19:14 UTC, mbostock requested changes
Can you add the D3 logo at the top of the README (like we do on d3/d3) and then use a complete sentence to introduce the library. You can copy the first paragraph from https://d3js.org/d3-force.

2023-10-05 19:33 UTC, Fil commented
OK, I've minimized it again ([preview](https://github.com/d3/d3-force/blob/7cb26713c7854909b54e8338aebf21e8fddbcba3/README.md)). Also, using the D3 logo from d3/d3 — would it be any better to have a local copy?

2023-10-06 00:45 UTC, mbostock approved these changes
I think you could keep the emoji in the bulleted list to be a little more “fun”. I like the conciseness of the list here.

2023-10-06 08:16 UTC, Fil commented
I tried emojis, and while I found them useful to identify sections in the long readme, I don't like them in the simple list (in particular, the emojis for "help" and "examples" are not evocative enough).

<img width="1028" alt="with emoji" src="https://github.com/d3/d3-force/assets/7001/84ac1ec1-4007-4e25-99a7-0cba3b649284">

2023-10-06 14:54 UTC, mbostock commented
I like the emojis just to make it a little less dry. We can add them later.

2023-10-06 14:54 UTC, merged